index:
    path: /
    controller: App\Controller\DefaultController::index
category:
    path: /category/{type}
    controller: App\Controller\CategoryController::show
contacts:
    path: /contacts
    controller: App\Controller\ContactController::showContacts

