index:
    path: /
    controller: App\Controller\DefaultController::index
category:
    path: /category/{slug}
    controller: App\Controller\CategoryController::show
contacts:
    path: /contacts
    controller: App\Controller\DefaultController::showContacts

